version: "2"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
      # - PLEX_CLAIM=
    networks:
      - plex-network
    ports:
      - "32400:32400"
    volumes:
      - ~/docker/plex_config/:/config
      - ~/firstPcloud/media/shows:/shows
      - ~/firstPcloud/media/movies:/movies
    restart: always
networks:
  plex-network:
    external:
      name: safe-network
