version: "2"
services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: always
    ports:
      - "7878:7878"
    networks:
      - torrentnet
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
    volumes:
      - ~/docker/radarr_config:/config 
      - ~/clouds/seedbox/files:/downloads #Seedbox downloads folder
      - ~/clouds/firstPcloud/media/movies:/movies
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: always
    ports:
      - "8989:8989"
    networks:
      - torrentnet
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
    volumes:
      -  ~/docker/sonarr_config:/config 
      - ~/clouds/firstPcloud/media/shows:/tv
      - ~/clouds/ftpSeedbox/files:/downloads
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: always
    networks:
      - torrentnet
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
    volumes:
      - ~/docker/jackett/jackett_config:/config
      - ~/docker/jackett/downloads:/downloads
    ports:
      - "9117:9117"
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    networks:
      - torrentnet
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
networks:
  torrentnet:
    driver: bridge
    enable_ipv6: False